src/main/java/com/ebenyx/template/jsf_spring/model/BaseEntity.java
package com.ebenyx.template.jsf_spring.model;

import java.io.Serializable;
import java.util.Date;
import java.util.Locale;
import java.util.Objects;
import javax.persistence.Column;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.MappedSuperclass;
import javax.persistence.PrePersist;
import javax.persistence.PreUpdate;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.apache.commons.lang3.builder.ToStringBuilder;
import org.ocpsoft.prettytime.PrettyTime;
import org.springframework.security.core.Authentication;
import org.springframework.security.core.context.SecurityContextHolder;

/**
 * @author alexwilfriedo
 */
@MappedSuperclass
public abstract class BaseEntity implements Serializable, Comparable<BaseEntity> {

    private final static PrettyTime PRETTY_TIME = new PrettyTime(new Locale("fr"));

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    protected Long id;

    @Column(nullable = false, updatable = false)
    @Temporal(TemporalType.TIMESTAMP)
    protected Date created;

    @Column
    @Temporal(TemporalType.TIMESTAMP)
    protected Date updated;

    @Column
    protected boolean enabled;

    @Column
    protected boolean viewed;
    
    @Column
    @Temporal(TemporalType.TIMESTAMP)
    protected Date viewedDate;

    @JoinColumn
    @ManyToOne(fetch = FetchType.LAZY)
    private Acteur creePar;

    @JoinColumn
    @ManyToOne(fetch = FetchType.LAZY)
    private Acteur modifierPar;

    transient protected boolean checked;

    transient protected boolean ignoreUpdateCreator;

    public BaseEntity() {
        viewed = false;
        enabled = true;
    }

    public Long getId() {
        return id;
    }

    public String getIdText() {
        return id + "";
    }

    public void setId(Long id) {
        this.id = id;
    }

    public boolean isViewed() {
        return viewed;
    }

    public boolean getViewed() {
        return viewed;
    }

    public void setViewed(boolean viewed) {
        this.viewed = viewed;
        if (this.viewed && viewedDate == null) {
            viewedDate = new Date();
        }
    }

    public boolean isChecked() {
        return checked;
    }

    public boolean getChecked() {
        return checked;
    }

    public void setChecked(boolean checked) {
        this.checked = checked;
    }

    public void toogleSelect() {
        this.checked = !checked;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 79 * hash + Objects.hashCode(this.id);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final BaseEntity other = (BaseEntity) obj;
        if (!Objects.equals(this.id, other.id)) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return ToStringBuilder.reflectionToString(this);
    }

    public boolean isEnabled() {
        return enabled;
    }

    public void setEnabled(boolean enabled) {
        this.enabled = enabled;
    }

    protected void onPrePersist() {
    }

    protected void onPreUpdate() {
    }

    protected void onPreSave() {
    }

    @PrePersist
    protected void _onPrePersist() {
        if (created == null) {
            created = new Date();
            updated = new Date();
        }
        onPrePersist();
        onPreSave();
    }

    @PreUpdate
    protected void _onPreUpdate() {
        updated = new Date();
        onPreUpdate();
        onPreSave();
    }

    public Date getCreated() {
        return created;
    }

    public void setCreated(Date created) {
        this.created = created;
    }

    public Date getUpdated() {
        return updated;
    }

    public void setUpdated(Date updated) {
        this.updated = updated;
    }

    public String getTimeCreatedAgo() {
        return prettyTime(getCreated());
    }

    public String getTimeUpdatedAgo() {
        return prettyTime(getUpdated());
    }

    public String prettyTime(Date date) {
        return PRETTY_TIME.format(date);
    }

    public Date getViewedDate() {
        return viewedDate;
    }

    public void setViewedDate(Date viewedDate) {
        this.viewedDate = viewedDate;
    }

    public Acteur getCreePar() {
        return creePar;
    }

    public void setCreePar(Acteur creePar) {
        this.creePar = creePar;
        this.modifierPar = modifierPar;
        this.setCreated(new Date());
        this.setUpdated(new Date());
    }

    public Acteur getModifierPar() {
        return modifierPar;
    }

    public void setModifierPar(Acteur modifierPar) {
        this.modifierPar = modifierPar;
        this.setUpdated(new Date());
    }

    @Override
    public int compareTo(BaseEntity o) {
        if (o == null) {
            return -1;
        }
        return o.getId().compareTo(o.getId());
    }

    public boolean getEnabled() {
        return enabled;
    }

    public Acteur getCurrentActeur() {
        Authentication authentication = SecurityContextHolder.getContext().getAuthentication();
        if (authentication.getPrincipal() instanceof Acteur) {
            return (Acteur) authentication.getPrincipal();
        }
        return null;
    }

    public boolean isIgnoreUpdateCreator() {
        return ignoreUpdateCreator;
    }

    public void setIgnoreUpdateCreator(boolean ignoreUpdateCreator) {
        this.ignoreUpdateCreator = ignoreUpdateCreator;
    }
}

src/main/java/com/ebenyx/template/jsf_spring/controller/ConfigController.java
/**
 *  (C) 2013-2014 Stephan Rauh http://www.beyondjava.net
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package com.ebenyx.template.jsf_spring.controller;

import org.slf4j.LoggerFactory;
import org.slf4j.Logger;

import com.ebenyx.template.jsf_spring.JsfUtil;
import com.ebenyx.template.jsf_spring.Main;
import com.ebenyx.template.jsf_spring.MyContext;
import com.ebenyx.template.jsf_spring.facade.AbstractFacade;
import com.ebenyx.template.jsf_spring.facade.ParametreFacade;
import com.ebenyx.template.jsf_spring.job.mail.Mail;
import com.ebenyx.template.jsf_spring.model.BaseEntity;
import com.ebenyx.template.jsf_spring.model.Parametre;
import com.ebenyx.template.jsf_spring.model.Acteur;
import com.ebenyx.template.jsf_spring.service.EmailService;
import com.google.gson.Gson;
import java.io.File;
import java.util.Arrays;
import java.util.List;
import java.util.Scanner;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.servlet.http.HttpServletRequest;
import org.apache.commons.io.FileUtils;
import org.primefaces.model.UploadedFileWrapper;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.mail.javamail.JavaMailSender;
import org.springframework.mail.javamail.JavaMailSenderImpl;
import org.springframework.security.authentication.AnonymousAuthenticationToken;
import org.springframework.security.core.Authentication;
import org.springframework.security.core.context.SecurityContextHolder;

@ManagedBean
@SessionScoped
public class ConfigController extends AbstractController<BaseEntity> {

    final static private Logger logger = LoggerFactory.getLogger(ConfigController.class);

    @Autowired
    private JavaMailSender emailSender;

    @Autowired
    private EmailService emailService;

    private Parametre parametre;

    @Autowired
    private ParametreFacade parametreFacade;

    @Autowired
    private MyContext myContext;

    @Autowired
    private HttpServletRequest request;

    private File currentFolder;

    @Override
    public AbstractFacade getFacade() {
        return parametreFacade;
    }

    public boolean isConnected() {
        Authentication authentication = SecurityContextHolder.getContext().getAuthentication();
        return (!(authentication instanceof AnonymousAuthenticationToken));
    }

    @Override
    public BaseEntity newEntity() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    public Parametre getParametre() {
        if (parametre == null) {
            parametre = parametreFacade.get();
        }
        return parametre;
    }

    public void reloadConfigJson() {
        set("configJson", new Gson().toJson(parametreFacade.get()));
    }

    public void saveConfigJson() {
        try {
            Gson gson = new Gson();
            Parametre parametre = gson.fromJson(getString("configJson"), Parametre.class);
            //remove config
            parametreFacade.builder().remove();
            parametreFacade.create(parametre);
            this.parametre = parametre;
            JsfUtil.msgSucces();
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    public void saveParam() {
        parametreFacade.edit(parametre);
        JsfUtil.msgSucces();
    }

    public Acteur getUserAct() {
        Authentication authentication = SecurityContextHolder.getContext().getAuthentication();
        if (authentication.getPrincipal() instanceof Acteur) {
            return (Acteur) authentication.getPrincipal();
        }
        return null;
    }

    public boolean getAnonymousUser() {
        Authentication authentication = SecurityContextHolder.getContext().getAuthentication();
        if (authentication.getPrincipal() instanceof String) {
            return "anonymousUser".equals(authentication.getPrincipal());
        }
        return false;
    }

    public void saveEmailParam() {
        try {
            parametre.setup((JavaMailSenderImpl) emailSender);
            emailService._sendSimpleMessage(
                    Mail.createNew()
                            .setTo(parametre.getMailTest())
                            .setSubject("EMAIL TEST")//config("app_name"))
                            .setTemplate("email-test.html")
            );
            saveParam();
        } catch (Exception ex) {
            parametreFacade.edit(parametre);
            ex.printStackTrace();
            JsfUtil.msgErreur("Echec de connexion !");
        }
    }

    public List<File> currentFolderContent() {
        if (get("currentFolderContent") == null) {
            set("currentFolderContent", Arrays.asList(getCurrentFolder().listFiles()));
        }
        return (List) get("currentFolderContent");
    }

    public void setCurrentFolder(File currentFolder) {
        unsetField("currentFolderContent");
        this.currentFolder = currentFolder;
    }

    public File getCurrentFolder() {
        if (currentFolder == null) {
            currentFolder = new File(myContext.getBasePath());
        }
        return currentFolder;
    }

    public void remplacerFileAndRestart() {
        if (_remplacerFile()) {
            redemarrer();
        }
    }

    public void remplacerFile() {
        _remplacerFile();
    }

    public boolean _remplacerFile() {
        try {
            UploadedFileWrapper fileWrapper = (UploadedFileWrapper) get("remplacerFile");
            if (fileWrapper == null) {
                JsfUtil.msgErreur("Impossible de joindre le fichier");
                return false;
            }
            FileUtils.copyInputStreamToFile(
                    fileWrapper.getInputstream(),
                    new File(String.format("%s/%s", getCurrentFolder().getAbsolutePath(), fileWrapper.getFileName()))
            );
            JsfUtil.msgSucces();
            unsetField("currentFolderContent");
            return true;
        } catch (Exception ex) {
            ex.printStackTrace();
            JsfUtil.msgErreur(ex.getMessage());
        }
        return false;
    }

    public void redemarrer() {
        Main.restart();
        JsfUtil.msgSucces("Redemerrage en cours ...");
        logger.info("redemerrage en cours ...");
    }

    public String handleCommand(String command, String[] params) {
        try {
            Runtime runtime = Runtime.getRuntime();
            Process process = runtime.exec(command + " " + String.join(" ", params), null, currentFolder);
            Scanner s = new Scanner(process.getInputStream());
            StringBuilder text = new StringBuilder();
            while (s.hasNextLine()) {
                text.append(s.nextLine());
                text.append("\r\n");
            }
            s.close();
            int result = process.waitFor();
            unsetField("currentFolderContent");
            return text.toString();
        } catch (Exception ex) {
            logger.error("", ex);
            return ex.getMessage();
        }
    }
}

src/main/webapp/WEB-INF/babylon/_menu.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:p="http://primefaces.org/ui">

    <p:menuitem value="Dashboard" icon="fa fa-fw fa-dashboard" update="mainContent" action="#{mainController.set('page','Dashboard')}" />
    <p:menuitem value="Moniteur" icon="fa fa-fw fa-dashboard" 
                update="mainContent" 
                action="#{mainController.set('page','Gestion des moniteurs')}" />

    
</ui:composition>

src/main/webapp/WEB-INF/babylon/_user_menu.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml" 
                xmlns:h="http://java.sun.com/jsf/html" 
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:p="http://primefaces.org/ui">
    <li>
        <p:commandLink  update="page" 
                        actionListener="#{mainController.set('page','profil')}"  >
            <i class="fa fa-fw fa-user"></i>
            <span>Profile</span>
        </p:commandLink>
    </li>
    <li>
        <p:commandLink rendered="#{mainController.currentActeur.can('role_admin')}" 
                       update="page" 
                       actionListener="#{mainController.set('page','Parametres')}"  >
            <i class="fa fa-fw fa-cog"></i>
            <span>Parametres</span>
        </p:commandLink>
    </li>
    <li>
        <p:commandLink
            oncomplete="window.location='/logout';"
            actionListener="#{mainController.logout('/logout')}">
            <i class="fa fa-fw fa-sign-out"></i>
            <span>Deconnexion</span>
        </p:commandLink>
    </li>
</ui:composition>

src/main/webapp/WEB-INF/babylon/footer.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml" xmlns:h="http://java.sun.com/jsf/html" xmlns:f="http://java.sun.com/jsf/core"
    xmlns:ui="http://java.sun.com/jsf/facelets" xmlns:p="http://primefaces.org/ui">

    <div class="ui-g">
        <div class="ui-g-6">
            <p:graphicImage name="images/logo-black.png" library="babylon-layout" />
        </div>
        <div class="ui-g-6 footer-icons"><b>#{bundle.app_name}</b></div>
    </div>
</ui:composition>

src/main/webapp/WEB-INF/babylon/groupedMenu.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml" 
                xmlns:h="http://java.sun.com/jsf/html" 
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:ui="http://java.sun.com/jsf/facelets" 
                xmlns:p="http://primefaces.org/ui" 
                xmlns:pb="http://primefaces.org/babylon">
    <pb:menu widgetVar="babylonMenuWidget">
        <ui:include src="./_menu.xhtml" />
    </pb:menu>
</ui:composition>

src/main/webapp/WEB-INF/babylon/menu.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml" xmlns:h="http://java.sun.com/jsf/html" xmlns:f="http://java.sun.com/jsf/core"
    xmlns:ui="http://java.sun.com/jsf/facelets" xmlns:p="http://primefaces.org/ui">

    <div class="layout-menu-container">
        <div class="layout-menu-logo">
            <h:form id="logoform">
                <h:outputLink  id="logolink"  value="/index.xhtml">
                    <p:graphicImage rendered="false" style="height: 50px;"
                        name="images/#{guestPreferences.darkLogo ? 'logo-black.png' : 'logo-white.png'}" 
                        library="babylon-layout" />
                    <span class="logo-text">
                        #{bundle.app_name}
                    </span>
                </h:outputLink >
            </h:form>
        </div>
        
        <div class="nano layout-menu-wrapper">
            <div class="nano-content menu-scroll-content">
                <h:form id="menuform">
                    <ui:fragment rendered="#{guestPreferences.profileMode == 'inline' ? true : false}">
                        <div class="layout-profile">
                            <a class="layout-profile-button" href="#">
                                <p:graphicImage name="images/avatar.png" library="babylon-layout" />
                                <div class="layout-profile-userinfo">
                                    <span class="layout-profile-name">Arlene Welch</span>
                                    <span class="layout-profile-role">Design Ops</span>
                                </div>
                                <i class="layout-profile-icon fa fa-angle-down"></i>
                            </a>
                            <ul class="layout-profile-menu">
                                <ui:include src="./_user_menu.xhtml" />
                            </ul>
                        </div>
                    </ui:fragment>
                    <ui:include src="#{guestPreferences.groupedMenu ? 'groupedMenu.xhtml' : 'ungroupedMenu.xhtml'}" />
                </h:form>
            </div>
        </div>
    </div>
</ui:composition>

src/main/webapp/WEB-INF/babylon/template.xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:p="http://primefaces.org/ui"
      lang="en">

    <h:head>
        <f:facet name="first">
            <meta http-equiv="X-UA-Compatible" content="IE=edge" />
            <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
            <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0"/>
            <meta name="apple-mobile-web-app-capable" content="yes" />
        </f:facet>
        <title><ui:insert name="title">#{bundle.app_name}</ui:insert></title>
        <h:outputScript name="js/nanoscroller.js" library="babylon-layout" />
        <h:outputScript name="js/layout.js" library="babylon-layout" />
        <ui:insert name="head"/>
        <style>
            KKONE
            body{
                color: #3e3e3e !important;
            }
            body .ui-dialog {
                padding: 0px 0px;
            }
            body .ui-dialog .ui-dialog-content {
                border-top: 1px solid #f1ecec;
            }
            .layout-main{
                background-color: #efecec;
                min-height: 450px !important;
            }
            .ui-outputlabel-rfi{
                color: red;
                font-weight: bold;
            }
            .ui-outputlabel{
                font-weight: bold;
            }

            .ui-dialog div[class^="ui-g-"],
            .ui-dialog div[class*=" ui-md-"],
            .ui-dialog div[class*=" ui-lg-"]{
                padding: 1px;
            }
            div[class^="ui-g-"]>label,
            div[class*=" ui-md-"]>label,
            div[class*=" ui-lg-"]>label{
                margin-bottom: 1px;
                margin-top: 3px;
            }

            .layout-wrapper .layout-menu-container .layout-menu-logo a img,
            .layout-wrapper .layout-topbar .layout-topbar-logo img {
                margin-top: 0px;
            }
            .italic{
                font-style: italic;
            }
            .right-align{
                text-align: right;  
            }
            .center-align{
                text-align: center;  
            }
            .left-align{
                text-align: left;  
            }
            .dialog-bottom{
                border-top: 1px solid lightgray;
            }
            body .ui-radiobutton span.ui-radiobutton-icon {
                margin-left: -6px !important;
            }
            .ui-datagrid-content,.ui-paginator{
                background: none;
                border:none;
            }
            .ui-datagrid .ui-paginator{
                text-align: right;
            }
            .fs-8{
                font-size: 8px;
            }
            .fs-10{
                font-size: 10px;
            }

            #loader {
                transition: all 0.3s ease-in-out;
                opacity: 1;
                visibility: visible;
                position: fixed;
                height: 100vh;
                width: 100%;
                background: #fff;
                z-index: 90000;
            }

            #loader.fadeOut {
                opacity: 0;
                visibility: hidden;
            }
            .float-left{
                float: left;
            }
            .float-right{
                float: right;
            }

            .spinner {
                width: 40px;
                height: 40px;
                position: absolute;
                top: calc(50% - 20px);
                left: calc(50% - 20px);
                background-color: #333;
                border-radius: 100%;
                -webkit-animation: sk-scaleout 1.0s infinite ease-in-out;
                animation: sk-scaleout 1.0s infinite ease-in-out;
            }

            @-webkit-keyframes sk-scaleout {
                0% { -webkit-transform: scale(0) }
                100% {
                    -webkit-transform: scale(1.0);
                    opacity: 0;
                }
            }

            @keyframes sk-scaleout {
                0% {
                    -webkit-transform: scale(0);
                    transform: scale(0);
                } 100% {
                    -webkit-transform: scale(1.0);
                    transform: scale(1.0);
                    opacity: 0;
                }
            }

            .h-2r, .sz-2r {
                height: 32px !important;
            }
            .sz-2r, .w-2r {
                width: 32px !important;
            }

            .layout-wrapper .route-bar .route-bar-right {
                padding: 6px 25px;
                display: inline-block;
                float: right;
            }
            .autocomplete-doc .ui-inputfield {
                padding: 2px !important;
            }
            .logo-text {
                -webkit-transition: width 0.3s ease-in-out;
                -o-transition: width 0.3s ease-in-out;
                transition: width 0.3s ease-in-out;
                display: block;
                float: left;
                height: 50px;
                font-size: 20px;
                line-height: 50px;
                text-align: center;
                width: 230px;
                font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
                padding: 0 15px;
                font-weight: 300;
                overflow: hidden;
                color: #fff;
                border-bottom: 0 solid transparent;
                font-weight: bolder;
            }
            .row-error-contact td{
                background-color: #ffc4c4;
            }
            /*
            .ui-datatable .ui-chkbox-all{
                display: none !important;
            }*/
            .uppercase{
                text-transform: uppercase;
            }
            .shaddow{
                box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2);
            }
            body .ui-datatable thead th {
                background-color: #e0e0e0;
            }
            body .ui-datatable thead th,
            body .ui-datatable .ui-datatable-data > tr{
                border-left: none;
                border-right: none;
            }
            body .ui-paginator {
                border-bottom:none;
                border-left:none;
                border-right:none;
                border:none;
                text-align: right;
            }
            .ui-datatable thead th, .ui-datatable tfoot td {
                text-align: left;
            }
            .layout-wrapper.layout-menu-dark .layout-menu-container {
                /*background: url(/javax.faces.resource/images/pages/sidebar.jpg.xhtml?ln=babylon-layout);*/
                background: black;
            }
        </style>
    </h:head>
    <h:body>
        <p:growl id="growll" >
            <p:autoUpdate/>
        </p:growl>
        <div class="layout-wrapper #{guestPreferences.menuMode} #{guestPreferences.menuColor} #{guestPreferences.orientationRTL ? 'layout-rtl' : null}">
            <ui:include src="./topbar.xhtml"></ui:include>
            <h:panelGroup id="page" >
                <ui:include src="./menu.xhtml"></ui:include>
                <h:panelGroup id="mainContent">
                    <ui:insert name="content"></ui:insert>
                </h:panelGroup>
            </h:panelGroup>
            <h:panelGroup rendered="#{mainController.currentActeur.hasRole('role_acces_param_maintenance')}"  >
                <ui:include 
                    src="./config.xhtml" />
            </h:panelGroup>

            <div class="layout-footer">
                <ui:include src="./footer.xhtml"></ui:include>
            </div>

            <div class="layout-mask"></div>
        </div>
        <h:form>
            <p:confirmDialog global="true" showEffect="fade" 
                             hideEffect="fade"
                             header="veuillez confirmer l'action" 
                             style="white-space: pre;" >
                <p:commandButton value="Non" type="button" styleClass="ui-confirmdialog-no" icon="ui-icon-close" />
                <p:commandButton value="Oui" type="button" styleClass="ui-confirmdialog-yes" icon="ui-icon-check" />
            </p:confirmDialog>
        </h:form>

        <p:ajaxStatus onstart="PF('statusDialog').show()" onsuccess="PF('statusDialog').hide()" />
        <p:dialog widgetVar="statusDialog" modal="true" draggable="false" closable="false" resizable="false" showHeader="false">
            <p:graphicImage library="images" name="loader.gif" />
        </p:dialog>
        <p:dialog widgetVar="StatusDialog" modal="true" draggable="false" closable="false" resizable="false" showHeader="false">
            <p:graphicImage library="images" name="loader.gif" />
        </p:dialog>

        <p:notificationBar position="top" 
                           effect="slide" 
                           styleClass="top" 
                           widgetVar="NotificationBar">
            <h:form id="NotificationForm" >
                <p:commandLink
                    style="margin-right: 10px;float: left; border-radius: 50%;display: inline-block;width: 20px;height:20px; background-color: red;color: black;text-align: center;"
                    value="X" 
                    onclick="PF('NotificationBar').hide()"/>
                <h:panelGroup>
                    Acceder au rapport de l'action via le lien suivant : 
                    <h:outputLink value="#{reportController.field.action_report_link}" >
                        Telecharger le rapport
                    </h:outputLink>
                </h:panelGroup>
            </h:form>
        </p:notificationBar>
        <h:outputStylesheet name="material-colors.min.css" library="css" />
        <h:outputStylesheet name="css/nanoscroller.css" library="babylon-layout" />
        <h:outputStylesheet name="css/primeflex.css" library="babylon-layout" />
        <h:outputStylesheet name="css/layout-#{guestPreferences.layout}.css" library="babylon-layout" />
        <h:outputScript  library="js" name="jsfcrud.js"/>
        <h:outputScript library="template3" name="vendor.js" />
        <h:outputScript library="template3" name="bundle.js" />
    </h:body>

</html>

src/main/webapp/WEB-INF/babylon/template2.xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:h="http://java.sun.com/jsf/html" xmlns:f="http://java.sun.com/jsf/core"
    xmlns:ui="http://java.sun.com/jsf/facelets" xmlns:p="http://primefaces.org/ui">

<h:head>
    <f:facet name="first">
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0" />
        <meta name="apple-mobile-web-app-capable" content="yes" />
    </f:facet>
    <title>#{title}</title>
    <style>
        .login-body .login-content img {
            margin-bottom: 60px;
        }
        .login-body{
            background: black !important;
        }
    </style>
</h:head>

<h:body styleClass="#{body_class}">
    <p:growl id="growl" >
        <p:autoUpdate/>
    </p:growl>
    <div class="#{panel_class}"></div>
    <div class="#{panel_content}">
        <p:graphicImage name="images/logo-black.png" library="babylon-layout" />
        <ui:insert name="content" />
    </div>
    
    <h:form>
            <p:confirmDialog global="true" showEffect="fade" 
                             hideEffect="fade"
                                    header="veuillez confirmer l'action" 
                             style="white-space: pre;" >
                <p:commandButton value="Non" type="button" styleClass="ui-confirmdialog-no" icon="ui-icon-close" />
                <p:commandButton value="Oui" type="button" styleClass="ui-confirmdialog-yes" icon="ui-icon-check" />
            </p:confirmDialog>
        </h:form>
    <h:outputStylesheet name="material-colors.min.css" library="css" />
    <h:outputStylesheet name="css/layout-#{guestPreferences.layout}.css" library="babylon-layout" />
    <h:outputScript library="template3" name="vendor.js" />
    <h:outputScript library="template3" name="bundle.js" />
    <h:outputScript  library="js" name="jsfcrud.js"/>
</h:body>

</html>